#cloud-config
#check private ip on exports
#match private network of worker nodes
#This runs on Centos 7+

package_upgrade: true

packages:
  - nfs-utils
  - nfs-utils-lib

runcmd:
- [ systemctl, enable, nfs-server.service ]
- [ systemctl, start, nfs-server.service ]

write_files:
  - path: /etc/exports
    content: |
      /mnt/volume_nyc1_01 <privateip/16>(rw,no_root_squash,no_subtree_check)